version: 0.1
phases:
  pre_build:
    commands:
      - echo -n "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo -n "$CODEBUILD_SOURCE_VERSION"
      - echo -n "$CODEBUILD_BUILD_ID"
      - echo -n "$REPOSITORY_URI"
      - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
  build:
    commands:
      - composer install
#      - docker build --tag "$(cat /tmp/build_tag.out)" .
  post_build:
    commands:
      - docker push "$(cat /tmp/build_tag.out)"
artifacts:
  files: /tmp/build.json
  discard-paths: yes
