version: '2'
services:
  app:
    build: .
    restart: 'unless-stopped'
    depends_on:
      - db
    volumes:
      - ./vendor:/var/www/vendor
      - ./src:/var/www/src
      - ./app:/var/www/app
      - ./web:/var/www/web
      - ./bin:/var/www/bin
      - ./entrypoint.sh:/var/www/entrypoint.sh
    environment:
      - SYMFONY__DATABASE_NAME=${DATABASE_NAME}
      - SYMFONY__DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SYMFONY__DATABASE_HOST=db
      - SYMFONY__DATABASE_USER=root
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/web
    depends_on:
      - app
    ports:
      - "80"
